# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ubuntu-22.04, ubuntu-20.04]
        # python-version: ["3.9", "3.10", "3.11"]

    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . 
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest -sv --cov --cov-report=term -p no:pytest_wampy tests

    # - name: Lint with ruff
    # - uses: actions/checkout@v3
    # - uses: chartboost/ruff-action@v1

    # - name: Ensure formatted with black
    # - uses: actions/checkout@v3
    # - uses: psf/black@stable
    #   with:
    #     options: "--check --verbose --max-line-length=120"
    #     src: "./dreamstream"